### ISSUE TITLE
UMC-2B

### ISSUE THREAD

**Issue by enriquemarquez** [adrianschlatter/threadlib#33]
I am trying to use the library to implement IEEE 1785.2a flange. UNC-2B do not appear in the thrads table. Is it possible to add?
![image](https://user-images.githubusercontent.com/10174923/76628725-1b111d80-6535-11ea-9614-ce5908713bc8.png)

**Comment by adrianschlatter** [comment]
threadlib already has UNC. 2B is the so-called class of the thread and specifies tolerance/allowance. threadlib does not distinguish classes as I considered this overkill for CAD-models that are usually intended for 3D-printing. You are lucky, though: threadlib threads were designed based on class 2 specs, therefore internal threads are 2B (external threads are 2A).
