### ISSUE TITLE
Internal thread vs 'difference'

### ISSUE THREAD

**Issue by sverzijl** [adrianschlatter/threadlib#41]
Putting some threads on my model. 

Are the 'internal threads (ie Mx-int) equivalent to using 'difference' with a bolt or external thread or is there some tolerance built into the internal threads?

**Comment by adrianschlatter** [comment]
Hi @sverzijl 

No, this is not equivalent. threadlib adds the tolerances required by the norms.


> Putting some threads on my model. 
> 
> 
> 
> Are the 'internal threads (ie Mx-int) equivalent to using 'difference' with a bolt or external thread or is there some tolerance built into the internal threads?
