### ISSUE TITLE
FreeCAD Compatibility

### ISSUE THREAD

**Issue by bvwj** [adrianschlatter/threadlib#45]
threadlib models do not seem to open in FreeCAD.

FreeCAD's OpenSCAD reader does not support all OpenSCAD functions.  My guess is threadib is using one of those unsupported functions.

If it were easy to work around, I find the FreeCAD interface very useful for things like generating .step models.

**Comment by gkatev** [comment]
Is threadlib installed in the library folder of OpenSCAD? (I don't know if it _has_ to be). It has always worked for me, the few times I have done it.

I just imported a simple BSP thread, by drag'n'dropping the .scad into FreeCAD. The library is in $HOME/.local/share/OpenSCAD/, and I'm using FreeCAD 0.18.16146, and OpenSCAD 2019.05
