### ISSUE TITLE
link in readme

### ISSUE THREAD

**Issue by yeKcim** [adrianschlatter/threadlib#59]
PCO-1881 pdf https://www.bevtech.org/assets/Committees/Packaging-Technology/20/3784253-20.pdf is out

**Comment by adrianschlatter** [comment]
Thanks for the notification. I'll try to read it later: Currently, their server is not responding.

**Comment by adrianschlatter** [comment]
bevtech.org still does not respond. Strange.

**Comment by twbaumann** [comment]
Try this link: https://www.isbt.com/assets/Committees/Packaging-Technology/21/3784253-21.pdf

**Comment by adrianschlatter** [comment]
threadlib's PCO-1881 is based on drawing no. 3784253-20. I checked drawing 3784253-21 and cannot find any difference apart from:

- drawing number
- formatting changes (such as shifting the text "SECTION J-J"

Not even the date changed.

Am I missing something?

**Comment by twbaumann** [comment]
I didn't see any difference either. Version 21 is listed on this page: https://www.isbt.com/threadspecs-downloads.asp. Perhaps the PCO-1881 spec is not yet officially finalized - just a guess.
