### ISSUE TITLE
Refactor nut to allow hex nut

### ISSUE THREAD

**Issue by amadeuspzs** [adrianschlatter/threadlib#61]
Currently you can modify https://github.com/adrianschlatter/threadlib/blob/d8c8384988c247c764ad47c504e5bbee5d55fc23/threadlib.scad#L60 to set `$fn=6` to obtain a hex nut:

![image](https://user-images.githubusercontent.com/534681/142411535-691a085e-f6af-4f0d-93cb-cd548b2275b5.png)

However, you don't want to pass `fn=6` into the `nut` module otherwise the resolution of the thread will be affected.

Can we refactor the `nut` module to allow for hex nuts?

**Comment by adrianschlatter** [comment]
How would you want to refactor nut(...)?
