### ISSUE TITLE
How do I make a 1/4" lag screw?

### ISSUE THREAD

**Issue by andrewmellinger** [adrianschlatter/threadlib#69]
Greetings! I am trying to make a hole for a 1/4 inch lag screw which is basically just a 1/4 inch wood screw.  I think these are AMSE threads?

Any idea how to find the 1/4 lag screw specs and translate to threads lib?

Thanks!

**Comment by adrianschlatter** [comment]
[Here](https://www.asme.org/codes-standards/find-codes-standards/b18-6-1-wood-screws/1981/drm-enabled-pdf)?
