### ISSUE TITLE
Can't open library 'thread_profile.scad'.

### ISSUE THREAD

**Issue by korpx** [adrianschlatter/threadlib#73]
Tring out "threadlib\tests\test.scad"

Getting the following warnings;
Can't open library 'thread_profile.scad'.
Ignoring unknown module 'straight_thread'

I can't find thread_profile.scad at all.

OpenSCAD Version: 2023.03.10 (git dbb29a268)
System information: Windows(TM) 10.0 SP 0.0 NTW 1 MSDN 724833 4 CPUs 15.88 GB RAM

**Comment by adrianschlatter** [comment]
Please re-read the[ installation instructions](https://github.com/adrianschlatter/threadlib) and try again.

**Comment by korpx** [comment]
That did it. Note to self: RTFM :) Thanks!
