### ISSUE TITLE
ignoring unknown module "nut"

### ISSUE THREAD

**Issue by LarsOde** [adrianschlatter/threadlib#88]
probably the error is on my side, since I'm really new to scad ;)
I'm trying to create a cap with small holes to replace the lost one of my garden pump, it has a 1/2" thread there. I installed all the libs that are mentioned, but get this error, and no output. Where should I start looking for the problem?
[WARNING: Ignoring unknown module 'nut' in file , line 1]
nut("G1/2", turns=4, Douter=16);

Edit: ok, should have read better ;) I missed the "use <threadlib/threadlib.scad>"
though now I get a different error:
WARNING: Can't open library 'thread_profile.scad'. 
I git-cloned the library from here:

C:\Program Files (x86)\OpenSCAD\libraries>git clone https://github.com/adrianschlatter/threadlib
Cloning into 'threadlib'...
remote: Enumerating objects: 455, done.
remote: Counting objects: 100% (168/168), done.
remote: Compressing objects: 100% (77/77), done.
remote: Total 455 (delta 110), reused 108 (delta 82), pack-reused 287
Receiving objects: 100% (455/455), 4.14 MiB | 22.76 MiB/s, done.
Resolving deltas: 100% (227/227), done.

(afterwards I noticed that scad uses a folder in "Documents", so I moved everything there)

**Comment by adrianschlatter** [comment]
Please read the installation section in the README carefully :-)
